[general]
import = ["./theme/tokyo-night-storm.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 3
padding.y = 0

dynamic_padding = true

decorations = "None"
opacity = 0.80
blur = true
decorations_theme_variant = "Dark"

[font]
normal.family = "MesloLGS Nerd Font"
size = 18

[colors]
cursor.cursor = "#C0CAF5"

[selection]
save_to_clipboard = true

[cursor]
blink_timeout = 0

[mouse]
hide_when_typing = true
